/**
 * Per-operator CORS verdicts for the live feed.
 *
 * In a static / frontend-only build the browser fetches CT logs directly, and
 * many logs don't serve `Access-Control-Allow-Origin` — those fail with a
 * CORSError.  CORS support is a property of the operator's serving
 * infrastructure, not the individual log, so we track it per operator and use
 * it to order the feed's default log selection (CORS-friendly operators first).
 *
 * This is a checked-in, shared verdict list rather than per-browser state, so
 * every visitor benefits without having to re-discover failures.  Regenerate it
 * by probing the live logs:
 *
 *     node update-cors-operators.mjs
 *
 * The OPERATOR_CORS block below (between the markers) is rewritten by that
 * script — don't hand-edit it; edit the script or re-run it instead.
 */

export type CorsStatus = 'ok' | 'blocked'

// cors-operators:begin — generated by update-cors-operators.mjs; do not edit by hand
export const OPERATOR_CORS: Record<string, CorsStatus> = {
  "Cloudflare": "blocked",
  "DigiCert": "ok",
  "Geomys": "ok",
  "Google": "ok",
  "IPng Networks": "ok",
  "Let's Encrypt": "blocked",
  "Sectigo": "blocked",
  "TrustAsia": "ok",
}
// cors-operators:end

/** Known CORS verdict for an operator, or undefined if we have none. */
export function getOperatorCors(operator?: string): CorsStatus | undefined {
  return operator ? OPERATOR_CORS[operator] : undefined
}
